config/routes.rb
Rails.application.routes.draw do

  devise_for :admin

  # Concerns ======================================

  concern :positionable do
    patch :position, on: :member
  end

  # Admin ======================================

  namespace :admin do
    resources :admins
    resources :basic_pages, concerns: :positionable
    resources :themes, concerns: :positionable
    resources :axes, concerns: :positionable
    resources :tags, concerns: :positionable
    resources :tool_categories, concerns: :positionable
    resources :trainings
    resources :training_tools, only: [:destroy], concerns: :positionable
    resources :comments, only: [:index, :destroy] do
      member do
        patch :accept 
        patch :reject
      end
    end
    resources :tools do
      member do
        patch :accept 
        patch :reject
        get :edit_part_1
        put :part_1
        get :edit_part_2
        put :part_2
      end
      resources :steps, controller: "tools/steps", only: [:destroy]
      resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
      resources :links, controller: "tools/links"
    end
    resources :seos, only: [:index, :edit, :update]
    root to: 'dashboard#index'
  end

  # Front ======================================
  
  resources :axes, only: [:index]
  resources :tools, only: [:index, :show, :new, :create, :update], 
    path: 'outils', path_names: {new: "nouveau"} do
    member do
      get :edit_part_1, path: "edition-1"
      put :part_1
      get :edit_part_2, path: "edition-2"
      put :part_2
      get :submission_success, path: "outil-soumis"
    end
    resources :comments, controller: "tools/comments", only: [:create]
    resources :steps, controller: "tools/steps", only: [:destroy]
    resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
    resources :links, controller: "tools/links"
    resources :trainings, controller: "tools/trainings", only: [:show], path: "parcours-formations"
  end
  resources :tags, only: [:index]
  resources :basic_pages, only: [:show], path: "pages"
  resource :sitemap, only: [:show]
  put "/accept_cookies", to: "home#accept_cookies"
  get "/:filename", to: "statics#show"

  root to: 'axes#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tool.rb
# frozen_string_literal: true

class Tool < ApplicationRecord
  # Configurations =============================================================
  include Sortable
  include Seoable

  # Nb de jours après sa création pdt lesquels un outil est considéré comme "nouveau"
  NOVELTY_DELAY = 15

  attr_accessor :current_step, :cgu_accepted

  # State machine -------------------------------------------------------------

  include AASM

  # états de publication et validation par l'admin
  #
  enum state: {
    draft:     0, # en attente de validation
    pending:   1, # en attente de validation
    accepted:  2, # accepté
    rejected:  3  # rejeté
  }

  aasm column: :state, enum: true do
    state :draft, initial: true
    state :pending
    state :accepted
    state :rejected

    event :submit, after: [:notify_submission] do
      transitions from: :draft, to: :pending
    end

    event :accept do
      transitions from: :draft, to: :accepted, if: :valid?
      transitions from: :pending, to: :accepted
      transitions from: :rejected, to: :accepted
    end

    event :reject do
      transitions from: :pending, to: :rejected
      transitions from: :accepted, to: :rejected
    end
  end

  private def notify_submission
    ToolSubmissionSnapshot.new(self).save
    AdminMailer.tool_submitted(self).deliver_now
  end

  # Enums ----------------------------------------------------------------------

  enum group_size: {
    size_1:  0, # 2-10
    size_2:  1, # 10-40
    size_3:  2  # + 40
  }

  enum duration: {
    duration_1:  0, # "5-30"
    duration_2:  1, # "30-60"
    duration_3:  2, # "60-120"
    duration_4:  3  # "120-240"
  }

  enum level: {
    easy:   0, 
    medium: 1, 
    hard:   2  
  }

  enum description_type: {
    description: 0,
    steps:       1
  }

  # Associations ===============================================================
  belongs_to :axis
  belongs_to :tool_category

  has_many :attachments,
           class_name: :'::Asset::ToolAttachment',
           as:         :assetable,
           dependent:  :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true

  has_many :tool_tags, dependent: :destroy
  has_many :tags, through: :tool_tags

  has_many :links, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :steps, -> { order 'steps.position' }, dependent: :destroy
  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

  has_many :training_tools, dependent: :destroy
  has_many :trainings, through: :training_tools

  # Callbacks ==================================================================
  
  # validation de présence de axe et catégorie -> directement en base

  validates :title, presence: true

  # Etape 2 du formulaire de création ----------------------------

  validates :goal,
            :teaser,
            :submitter_firstname,
            :submitter_lastname,
            :submitter_email,
            presence: true, unless: :is_step_1?

    validates :cgu_accepted,
          acceptance: {message: "doivent être acceptées"},
          unless: :is_step_1?

  private def description_exists?
    return true if (self.steps? and steps.any?) || (self.description? and description.present?)
    errors.add(:description, 'doit être renseignée')
    false
  end
  validate :description_exists?, unless: :is_step_1?

  private def is_step_1?
    current_step.to_i == 1
  end


  # Scopes =====================================================================

  scope :enabled, -> { accepted }

  # Filtres --------------------------------------------------------------------
  scope :by_title, ->(val) {
    val.downcase!
    where(arel_table[:title].matches("%#{val}%"))
  }

  scope :by_axis, ->(val) { where axis: val }
  scope :by_tool_category, ->(val) { where tool_category: val }

  scope :by_tag_ids, ->(id) {
    tt = ToolTag.arel_table
    condition = ToolTag
                .where(tt[:tag_id].in(id).and(tt[:tool_id].eq(arel_table[:id])))
                .exists
    where(condition)
  }

  scope :by_state, ->(state) {
    where(state: states.fetch(state.to_sym))
  }

  scope :by_format_type, ->(format) {
    # pour que le scope fonctionne qu'on renvoit la clé ou le code numerique du format
    format = ::Asset::ToolAttachment.format_types[format] unless format.is_a?(Integer)
    attachment_condition = ::Asset::ToolAttachment.arel_table[:format_type].eq(format)
    link_condition = ::Link.arel_table[:format_type].eq(format)

    eager_load(:attachments).eager_load(:links)
                            .where(attachment_condition.or(link_condition))
  }

  scope :by_duration, ->(val) { where(duration: durations.fetch(val.to_sym)) }
  scope :by_group_size, ->(val) { where(group_size: group_sizes.fetch(val.to_sym)) }
  scope :by_level, ->(val) { where(level: levels.fetch(val.to_sym)) }

  scope :by_theme, ->(val) {
    joins(:axis).merge(Axis.by_theme(val))
  }

  # Nouveautés ----------------------------------------------------------------

  scope :recent, -> {
    novelty_datetime = NOVELTY_DELAY.days.ago
    where(arel_table[:created_at].gt(novelty_datetime))
  }

  # Class Methods ==============================================================

  def self.apply_filters(params)
    klass = self

    klass = klass.by_title(params[:by_title]) if params[:by_title].present?
    klass = klass.by_theme(params[:by_theme]) if params[:by_theme].present?
    klass = klass.by_axis(params[:by_axis]) if params[:by_axis].present?
    klass = klass.by_tool_category(params[:by_tool_category]) if params[:by_tool_category].present?
    klass = klass.by_tag_ids(params[:by_tag_ids]) if params[:by_tag_ids].present?
    klass = klass.by_state(params[:by_state]) if params[:by_state].present?
    klass = klass.by_duration(params[:by_duration]) if params[:by_duration].present?
    klass = klass.by_group_size(params[:by_group_size]) if params[:by_group_size].present?
    klass = klass.by_level(params[:by_level]) if params[:by_level].present?
    klass = klass.by_format_type(params[:by_format_type]) if params[:by_format_type].present?

    klass.apply_sorts(params)
  end

  # Instance Methods ===========================================================

  def recent?
    created_at > NOVELTY_DELAY.days.ago
  end

  def random_training
    return nil unless trainings.any?
    @random_training ||= self.trainings.order('random()').first
  end

  def description_for_seo
    self.teaser
  end

  # private #=====================================================================
end

app/controllers/admin/tools/base_controller.rb
# frozen_string_literal: true

class Admin::Tools::BaseController < Admin::BaseController
  before_action :load_tool

  private

  def load_tool
    @tool = Tool.from_param(params[:tool_id])
  end
end

app/controllers/admin/tools/links_controller.rb
# frozen_string_literal: true

class Admin::Tools::LinksController < Admin::Tools::BaseController
  respond_to :json

  before_action :find_link, only: %i(edit update destroy)

  def index
    @links = @tool.links.apply_filters(params)
    render json: @links, eachSerializer: LinkSerializer
  end

  def new
    @link = @tool.links.new
    render layout: false
  end

  def create
    @link = @tool.links.new(link_params)
    if @link.save
      render json: @link, serializer: LinkSerializer
    else
      render :new, layout: false, status: 422
    end
  end

  def edit
    # @tool = @link.tool
    render layout: !request.xhr?
  end

  def update
    if @link.update(link_params)
      render json: @link, serializer: LinkSerializer
    else
      render :edit, layout: false, status: 422

    end
  end

  def destroy
    if @link.destroy
      render json: { id: params[:id] }
    else
      render status: :unprocessable_entity, json: { errors: @link.errors.full_messages }
    end
  end

  private # ----------------------------------------

  def link_params
    # params.require(:link_asset)
    params
      .fetch(:link) { {}.with_indifferent_access } # peut être vide
      .permit :id,
              :url,
              :title,
              :format_type,
              :tool_id
  end

  def find_link
    @link = Link.find(params[:id])
  end
end

app/controllers/admin/tools/steps_controller.rb
# frozen_string_literal: true

class Admin::Tools::StepsController < Admin::Tools::BaseController
  def destroy
    @step = @tool.steps.find(params[:id])
    if @step.destroy
      render json: { id: params[:id] }
    else
      render status: :unprocessable_entity, json: { errors: @step.errors.full_messages }
    end
  end
end

app/controllers/admin/tools/tool_attachments_controller.rb
# frozen_string_literal: true

class Admin::Tools::ToolAttachmentsController < Admin::Tools::BaseController
  respond_to :json

  before_action :find_attachement, only: %i(edit update destroy)

  def index
    @attachments = @tool.attachments.order(position: :asc)
    render json: @attachments, eachSerializer: ToolAttachmentSerializer
  end

  def create
    @attachment = @tool.attachments.new(attachment_params)
    if @attachment.save
      render json: @attachment, serializer: ToolAttachmentSerializer
    else
      render status: 304, json: { errors: @attachment.errors.full_messages }
    end
  end

  def edit
    render layout: false
  end

  def update
    if @attachment.update(attachment_params)
      render json: @attachment, serializer: ToolAttachmentSerializer
    else
      render status: 304, json: { errors: @attachment.errors.full_messages }
    end
  end

  def destroy
    if @attachment.destroy
      render json: { id: params[:id] }
    else
      render status: :unprocessable_entity, json: { errors: @attachment.errors.full_messages }
    end
  end

  private # ----------------------------------------

  def attachment_params
    # params.require(:attachment_asset)
    params
      .fetch(:asset_tool_attachment) { {}.with_indifferent_access } # peut être vide
      .permit :id,
              :asset,
              :title,
              :custom_file_name,
              :format_type,
              :assetable_id
  end

  def find_attachement
    @attachment = Asset::ToolAttachment.find(params[:id])
  end
end

app/controllers/tools/base_controller.rb
# frozen_string_literal: true

class Tools::BaseController < ApplicationController
  before_action :load_tool

  private

  def load_tool
    @tool = Tool.from_param(params[:tool_id])
  end
end

app/controllers/tools/comments_controller.rb
# frozen_string_literal: true

class Tools::CommentsController < Tools::BaseController
  
  def create
    @comment = @tool.comments.new(comment_params)
    if @comment.save
      render json: true
    else
      # render partial: 'comments/form', locals: {}, status: 422
      render status: 422, json: { errors: @comment.errors.full_messages }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:nickname, :organization, :content)
  end
end

app/controllers/tools/steps_controller.rb
# frozen_string_literal: true

class Tools::StepsController < Tools::BaseController
  def destroy
    @step = @tool.steps.find(params[:id])
    if @step.destroy
      render json: { id: params[:id] }
    else
      render status: :unprocessable_entity, json: { errors: @step.errors.full_messages }
    end
  end
end

app/controllers/tools/trainings_controller.rb
# frozen_string_literal: true

class Tools::TrainingsController < Tools::BaseController
  
  def show
    @training = @tool.trainings.from_param params[:id]
    @tools = @training.tools.enabled
                          .apply_filters(params)
                          .includes(:axis)
                          .includes(:seo)
                          .includes(:tool_category)
                          .includes(:tool_tags)
                          .includes(:tags)
                          .paginate(per_page: 20, page: params[:page])
  end

  private

end

app/helpers/tool_helper.rb
# frozen_string_literal: true

module ToolHelper

  DEFAULT_BLANK = "N.A."
  
  # Etat -----------------------------------------------

  def tool_state_title(state)
    I18n.t(state, scope: %i(tool_states title))
  end

  def tool_state_style(state)
    I18n.t(state, scope: %i(tool_states style))
  end

  def tool_state_options(states = Tool.states.keys)
    states.map do |state|
      [tool_state_title(state), state.to_s]
    end
  end

  # Taille groupe -----------------------------------

  def tool_group_size(group_size)
    return DEFAULT_BLANK if group_size.blank?
    I18n.t(group_size, scope: [:tool_group_sizes])
  end

  def tool_group_size_options(group_sizes = Tool.group_sizes.keys)
    group_sizes.map do |group_size|
      [tool_group_size(group_size), group_size.to_s]
    end
  end

  # Durée -------------------------------------------

  def tool_duration(duration)
    return DEFAULT_BLANK if duration.blank?
    I18n.t(duration, scope: [:tool_durations])
  end

  def tool_duration_options(durations = Tool.durations.keys)
    durations.map do |duration|
      [tool_duration(duration), duration.to_s]
    end
  end

  # Niveau difficulté -------------------------------------------

  def tool_level(level)
    return DEFAULT_BLANK if level.blank?
    I18n.t(level, scope: [:tool_levels])
  end

  def tool_level_options(levels = Tool.levels.keys)
    levels.map do |level|
      [tool_level(level), level.to_s]
    end
  end

  # Description type -------------------------------------------

  def tool_description_type_title(type)
    I18n.t(type, scope: [:tool_description_types])
  end

  # Tool Tag ===============================================================

  def tool_tags_options(tags = Tag.all)
    tags.order(:title).map { |tag| [tag.title, tag.id] }
  end

  # Tool Help ===============================================================

  def help_title(helpInstance)
    if helpInstance.present? && helpInstance.title.present?
      helpInstance.title
    else
      "Comment renseigner le champ \"#{I18n.t(helpInstance.field, scope: %i(helpers label tool)).downcase}\" ?"
    end
  end


  # Embedded Link ===============================================

  def embedded_content(link)
    raw(link.oembed_resource.html)
  end


  # Public cible -------------------------------------------

  # def tool_public(public)
  #   I18n.t(public, scope: [:tool_publics])
  # end

  # def tool_public_options(publics = Tool.publics.keys)
  #   publics.map do |public|
  #     [tool_public(public), public.to_s]
  #   end
  # end

  # Licence -------------------------------------------

  # def tool_licence(licence)
  #   I18n.t(licence, scope: [:tool_licences, :short])
  # end

  # def tool_licence_explanation(licence)
  #   I18n.t(licence, scope: [:tool_licences, :explanation])
  # end

  # def tool_licence_options(licences = Tool.licences.keys)
  #   licences.map do |licence|
  #     [tool_licence(licence), licence.to_s]
  #   end
  # end

  # def tool_licence_tooltip(licences = Tool.licences.keys)
  #   array = licences.map do |licence|
  #     [tool_licence(licence), tool_licence_explanation(licence)].join(" : ")
  #   end
  #   raw array.join("</br>")
  # end
end

app/views/tools/_help_popover.html.slim
- help = ToolHelp.get(field)
- if help.present? && help.with_content?
  = link_to "?", "javascript:void(0)", class:"help-link", data: {is_popover: true, content: text_to_html(help.content)}, title: help_title(help), tabindex: -1

app/views/tools/_layout_forms.html.slim
h1 Proposer un outil


.wizard-container
  ol.wizard-progress
    - if @tool.new_record?
      = menu_link "1", new_tool_path, section: :part_1, title: "Etape actuelle" ,li_class: 'wizard-step',  class: ""
      = menu_link "2", "javascript:void(0)", section: :part_2, title: "Aller à l'étape 2", li_class: 'wizard-step disabled',  class: " disabled", aria: {disabled: true}

    - else
      = menu_link "1", edit_part_1_tool_path(@tool), section: :part_1, title: "Aller à l'étape 1" ,li_class: 'wizard-step',  class: ""
      = menu_link "2", edit_part_2_tool_path(@tool), section: :part_2, title: "Aller à l'étape 2", li_class: 'wizard-step'


= yield

app/views/tools/_part_1_form.html.slim
= f.hm_form_errors
= f.hidden_field :current_step, value: 1

.form-group.required
  = f.label :title, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :title}
  = f.text_field :title, class: "form-control required", autofocus: true


.form-group.required
  = f.label :axis_id, value: "Axe thématique", class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :axis_id}
  .row.lg-gutter
    - current_theme.axes.enabled.each do |axis|
      .col-lg-3.col-md-4.col-sm-6.col-12.lg-gutter.form-card-col class="form-card-col-#{axis.id_key}"
        = f.radio_button :axis_id, axis.id, class: "hidden-error"
        = f.label :axis_id, value: axis.id, class: "form-card form-axis-card hidden-error", data: {is_axis_tooltip: axis.description} do
          span.form-axis-card_title= axis.title

.form-group
  = f.label :duration, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :duration}
  .row.lg-gutter
    - tool_duration_options.each do |title, id|
      .col-lg-3.col-md-4.col-sm-6.col-12.lg-gutter.form-card-col
        = f.radio_button :duration, id, class: "hidden-error"
        = f.label :duration, value: id, class: "card form-card hidden-error", data:{ uncheckable: true } do
          span.form-axis-card_title= title

.form-group
  = f.label :group_size, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :group_size}
  .row.lg-gutter
    - tool_group_size_options.each do |title, id|
      .col-lg-3.col-md-4.col-sm-6.col-12.lg-gutter.form-card-col
        = f.radio_button :group_size, id, class: "hidden-error"
        = f.label :group_size, value: id, class: "card form-card  hidden-error", data:{ uncheckable: true } do
          span.form-axis-card_title= title

.form-group
  = f.label :level, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :level}
  .row.lg-gutter
    - tool_level_options.each do |title, id|
      .col-lg-3.col-md-4.col-sm-6.col-12.lg-gutter.form-card-col
        = f.radio_button :level, id, class: "hidden-error"
        = f.label :level, value: id, class: "card form-card  hidden-error", data:{ uncheckable: true } do
          span.form-axis-card_title= title

.form-group.required
  = f.label :tool_category_id, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :tool_category_id}
  .row
    .col-lg-6
      = f.select :tool_category_id, tool_category_options, {include_blank: "Sélectionner une catégorie"}, class: "form-control required", data: {is_autocomplete_select: 'tool-category'}

.form-group
  = f.label :public, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :public}
  = f.text_field :public, class: "form-control"


.form-group
  = f.label :tag_ids, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :tag_ids}
  = f.select :tag_ids, tool_tags_options, {prompt: "Rechercher un mot-clé"}, multiple: true,  class: "form-control ",  data: {is_autocomplete_select: 'tag', path: tags_path}     

.d-flex.flex-row-reverse
  .p-6
    => f.submit "Etape suivante", class: "btn btn-inverse uppercase"

coffee:
  new PartOneToolForm()

app/views/tools/_part_2_form.html.slim
= f.hm_form_errors

.form-group.required
  = f.label :goal, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :goal}
  = f.text_area :goal, class: "form-control required", rows: 3, autofocus: true

.form-group.required
  = f.label :teaser, class:" form-control-label"
  = render partial: 'help_popover', locals: {field: :teaser}
  = f.text_area :teaser, class: "form-control", rows: 3


/ DESCRIPTION =========================================================

div#description-wrapper.mt-30
  .form-group.row.required
    .col-md-4
      = f.label :description, class:"label-title form-control-label"
      p.form-text.text-muted.small: em Choisir description simple ou par étapes
    .col-md-8
      .btn-group data-toggle="buttons"
        - Tool.description_types.keys.each do |description_type|
          - is_selected = f.object.description_type == description_type.to_s
          = label_tag :description_global, "Marche à suivre", class:"btn btn-secondary #{'active' if is_selected}", \
            data: {toggle: 'collapse', parent: "#description-wrapper", target: "##{description_type.to_s}"}, \
            aria: { controls: description_type.to_s, expanded: is_selected} do
            => f.radio_button :description_type, description_type.to_s
            => tool_description_type_title(description_type)
      = render partial: 'help_popover', locals: {field: :description}

  div#description.collapse class="#{'show' if f.object.description_type == 'description'}" data-is-description="#{f.object.steps.count}"
    .form-group.row
      .col-md-2: label Description simple
      .col-md-10
        = f.text_area :description, class: "form-control", rows: 8


  div#steps.collapse class="#{'show' if f.object.description_type == 'steps'}" 
    div data-is-step-list=true
      = f.fields_for :steps do |sf|
        .form-group.row data-is-step-idx="#{sf.index}" data-is-step="#{sf.object.id}"
          = sf.hidden_field :id
          .col-md-2: label = "Etape #{sf.index + 1}"
          .col-md-8
            = sf.text_area :description, class: "form-control", rows: 5
          .col-md-2.pull-right
            - unless sf.object.new_record?
              = link_to tool_step_path(f.object, sf.object), method: :delete, remote: true, data: {delete_step: 'persisted'}, class: 'btn btn-danger pull-right' do
                i.fa.fa-trash
            / - if sf.object.new_record?
              / = link_to "javascript:void(0)", data: {delete_step: sf.index}, class: 'btn btn-danger mb-2 pull-right' do
                i.fa.fa-trash  

    .form-group.row
      .col-md-8.offset-md-2
        = link_to "Ajouter une étape", "javascript:void(0)", data: {step_btn: 'delete'}, class: 'btn btn-inverse mb-2'


.form-group
  = f.label :advice
  = render partial: 'help_popover', locals: {field: :advice}
  = f.text_area :advice, class: "form-control", rows: 6

.form-group
  = f.label :material
  = render partial: 'help_popover', locals: {field: :material}
  = f.text_area :material, class: "form-control", rows: 6

.form-group
  = f.label :source
  = render partial: 'help_popover', locals: {field: :source}
  = f.text_field :source, class: "form-control"

.form-group
  = f.label :licence
  = render partial: 'help_popover', locals: {field: :licence}
  = f.text_field :licence, class: "form-control"

.row.mt-5
  .col-12.col-lg-6
    div class="d-flex justify-content-between"
      .label-title  Support
      = label_tag :"asset_tool_attachment[asset]"
        span.btn.btn-inverse.btn-sm.uppercase.mr-2
          | Ajouter un support
        = file_field_tag :"asset_tool_attachment[asset]", data: {file_upload: true, url: tool_attachments_path(f.object), method: 'POST', type: 'script'}, style: "display:none"
        / / filtre "accept" mal géré pour certains navigateurs (dont le mien pour les doc, xls, etc)
        / = file_field_tag :"asset_tool_attachment[asset]", accept: Asset::ToolAttachment::VALID_CONTENT_TYPES.map(&:to_s).join(','), data: {file_upload: true, url: tool_attachments_path(f.object), method: 'POST', type: 'script'}, style: "display:none"
        = render partial: 'help_popover', locals: {field: :tool_attachment}
    p.form-text.text-muted.small: em Formats autorisés : .pdf, .jpeg, .gif, .png, .doc, .xls, .ppt, .mp3, .wav
    p.form-text.text-muted.small: em Taille maximum : 8 Mo

    div.item-list.row data-is-media-list=true data-list-url="#{tool_attachments_path(f.object)}"

  .col-12.col-lg-6
    div class="d-flex justify-content-between"
      .label-title Liens
      div
        = link_to new_tool_link_path(@tool), remote: true,
          data: {link_btn: 'new'}, class: 'btn btn-inverse btn-sm uppercase mr-2' do
          | Ajouter un lien
        = render partial: 'help_popover', locals: {field: :link}

    div.item-list.row data-is-link-list="#{@tool.id}" data-list-url="#{tool_links_path(@tool)}"


div.mt-5
  = render partial: 'help_popover', locals: {field: :contact}
  .label-title  Contact
.row.input-margin-sm
  .col-6
    .form-group.required
      = f.label :submitter_email
      // = render partial: 'help_popover', locals: {field: :submitter_email}
      = f.text_field :submitter_email, class: "form-control required"
      // p.form-text.text-muted.small: em Pour que nous puissions vous recontacter si nécessaire. Ne sera pas affiché sur la fiche outil.

  .col-6
    .form-group
      = f.label :submitter_organization
      = render partial: 'help_popover', locals: {field: :submitter_organization}
      = f.text_field :submitter_organization, class: "form-control"
      // p.form-text.text-muted.small: em Optionnel, affiché sur la fiche outil si renseigné.

.row.input-margin-sm
  .col-6
    .form-group.required
      = f.label :submitter_firstname
      = render partial: 'help_popover', locals: {field: :submitter_firstname}
      = f.text_field :submitter_firstname, class: "form-control required"
      // p.form-text.text-muted.small: em Pour que nous puissions vous recontacter si nécessaire. Ne sera pas affiché sur la fiche outil.

  .col-6
    .form-group.required
      = f.label :submitter_lastname
      = render partial: 'help_popover', locals: {field: :submitter_lastname}
      = f.text_field :submitter_lastname, class: "form-control required"
      //  p.form-text.text-muted.small: em Optionnel, affiché sur la fiche outil si renseigné.

.form-check
  => f.label :hide_contact, class: "form-check-label" do
    => f.check_box :hide_contact, class: "form-check-input"
    span.ml-2  Merci de garder mes données confidentielles et de ne pas les publier sur la fiche outil

.form-check.mt-5.required
  = f.label :cgu_accepted, class: "form-check-label" do
    => f.check_box :cgu_accepted, class: "form-check-input required"
    span.ml-2> J'ai lu et accepte les
    => link_to " conditions générales d'utilisation de La fabrique du monde", "#", target: "_blank"
    //# => link_to "conditions générales d'utilisation de La fabrique du monde", get_basic_page_path(:cgu), target: "_blank"

.row.mt-5
  .col-6
    => f.submit name: "previous", value: "Etape précédente", class: "btn btn-inverse uppercase"
  .col-6.text-right
    => f.submit name: "continue", value: 'Enregistrer et continuer', class: "btn btn-default uppercase mr-2"
    => f.submit "Envoyer", class: "btn btn-inverse uppercase"


= render "tools/steps/hb_new"
= render "tools/tool_attachments/new"
= render "tools/tool_attachments/hb_thumbs"
= render "tools/links/hb_thumb"


coffee:
  $ ->
    new PartTwoToolForm()