config/routes.rb
Rails.application.routes.draw do

  devise_for :admin

  # Concerns ======================================

  concern :positionable do
    patch :position, on: :member
  end

  # Admin ======================================

  namespace :admin do
    resources :admins
    resources :basic_pages, concerns: :positionable
    resources :themes, concerns: :positionable
    resources :axes, concerns: :positionable
    resources :tags, concerns: :positionable
    resources :tool_categories, concerns: :positionable
    resources :trainings
    resources :training_tools, only: [:destroy], concerns: :positionable
    resources :comments, only: [:index, :destroy] do
      member do
        patch :accept 
        patch :reject
      end
    end
    resources :tools do
      member do
        patch :accept 
        patch :reject
        get :edit_part_1
        put :part_1
        get :edit_part_2
        put :part_2
      end
      resources :steps, controller: "tools/steps", only: [:destroy]
      resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
      resources :links, controller: "tools/links"
    end
    resources :seos, only: [:index, :edit, :update]
    root to: 'dashboard#index'
  end

  # Front ======================================
  
  resources :axes, only: [:index]
  resources :tools, only: [:index, :show, :new, :create, :update], 
    path: 'outils', path_names: {new: "nouveau"} do
    member do
      get :edit_part_1, path: "edition-1"
      put :part_1
      get :edit_part_2, path: "edition-2"
      put :part_2
      get :submission_success, path: "outil-soumis"
    end
    resources :comments, controller: "tools/comments", only: [:create]
    resources :steps, controller: "tools/steps", only: [:destroy]
    resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
    resources :links, controller: "tools/links"
    resources :trainings, controller: "tools/trainings", only: [:show], path: "parcours-formations"
  end
  resources :tags, only: [:index]
  resources :basic_pages, only: [:show], path: "pages"
  resource :sitemap, only: [:show]
  put "/accept_cookies", to: "home#accept_cookies"
  get "/:filename", to: "statics#show"

  root to: 'axes#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/admins/_form.html.slim
= f.hm_form_errors
= f.hm_text_field :email, {}, {class: "required"}

.form-group.row
  .form-label-default
    = f.label :password
  .controls-default
    = f.password_field :password, class: "required form-control"


.form-group.row
  .form-actions
    hr
    => f.submit button_name, class: "btn btn-primary", style: "margin-right: 2px", id: "submit_and_leave"
    => f.submit name: "continue", value: "#{button_name_2}", class: "btn btn-default", style: "margin-right: 2px", id: "submit_and_stay"
    = link_to "Annuler", admin_admins_path, class: "btn"

.form-group.row
  label.form-label-default
  .controls-default
    small: em.text-muted Les champs marqués d'une * sont obligatoires

app/views/admin/admins/_layout_form.html.slim
- content_for :current_navigation_section, :admins

.title-block
  h1
    | Gestion des admins
    = link_to admin_admins_path, class: 'btn btn-default float-right' do
      
      .glyphicon.glyphicon-arrow-left
      |  Retour

.card
  - if !@admin.new_record?

    h2.card-header
      | Edition de l'admin
      em=< @admin.email

    .card-block
      .row
        .col-md-2.border-right
          dl
            dt Date création :
            dd= l @admin.created_at.to_date
            dt Dernière mise à jour :
            dd= l @admin.updated_at
        .col-md-10
          = yield

  - else
    h2.card-header Créer un nouvel admin

    .card-block
      = yield

app/views/admin/admins/_layout_index.html.slim
- content_for :current_navigation_section, :admins

.title-block
  h1 
    | Gestion des admins

    = link_to new_admin_admin_path, class: "btn btn-info float-right" do
      span.glyphicon.glyphicon-plus>
      | Ajouter un admin

.card.card-block
  .content-main
    small.float-right = I18n.t("results", count: @admins.count)
    = yield

app/views/admin/admins/edit.html.slim
= render layout: 'layout_form' do
  = form_for @admin, as: :admin, url: admin_admin_path(@admin), html: {class: "form-horizontal"} do |f| 
    = render partial: "form", locals: {f: f, button_name: "Enregistrer les modifications", button_name_2: "Enregistrer et continuer l'édition"}

app/views/admin/admins/index.html.slim
= render layout: 'layout_index' do 

  table.table.table-striped.table-hover.table-sm
    thead.thead-inverse
      tr
        th Email
        th 
    tbody
      - @admins.each do |admin| 
        tr
          td= admin.email
          td.action-btns
            => link_to edit_admin_admin_path(admin), 
                        class: "btn btn-sm btn-info", 
                        title: "Editer" do

              span.glyphicon.glyphicon-pencil
            - if admin.id != current_admin.id
              = link_to admin_admin_path(admin),
                        method: :delete, 
                        data: {confirm: "Confirmer la suppression ?"}, 
                        title: "Supprimer", 
                        class: "btn btn-sm btn-danger" do 

                span.glyphicon.glyphicon-trash
      
      - if @admins.empty?
        tr
          td colspan="7"
            p.text-center: em.text-muted Aucun résultat


  = will_paginate @admins, renderer: WillPaginateBoostrap4Renderer

app/views/admin/admins/new.html.slim
= render layout: 'layout_form' do 
  = form_for @admin, as: :admin, url: admin_admins_path, html: {class: "form-horizontal"} do |f| 
    = render partial: "form", locals: {f: f, button_name: "Créer l'admin", button_name_2: "Créer et continuer l'édition"}