config/routes.rb
Rails.application.routes.draw do

  devise_for :admin

  # Concerns ======================================

  concern :positionable do
    patch :position, on: :member
  end

  # Admin ======================================

  namespace :admin do
    resources :admins
    resources :basic_pages, concerns: :positionable
    resources :themes, concerns: :positionable
    resources :axes, concerns: :positionable
    resources :tags, concerns: :positionable
    resources :tool_categories, concerns: :positionable
    resources :trainings
    resources :training_tools, only: [:destroy], concerns: :positionable
    resources :comments, only: [:index, :destroy] do
      member do
        patch :accept 
        patch :reject
      end
    end
    resources :tools do
      member do
        patch :accept 
        patch :reject
        get :edit_part_1
        put :part_1
        get :edit_part_2
        put :part_2
      end
      resources :steps, controller: "tools/steps", only: [:destroy]
      resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
      resources :links, controller: "tools/links"
    end
    resources :seos, only: [:index, :edit, :update]
    root to: 'dashboard#index'
  end

  # Front ======================================
  
  resources :axes, only: [:index]
  resources :tools, only: [:index, :show, :new, :create, :update], 
    path: 'outils', path_names: {new: "nouveau"} do
    member do
      get :edit_part_1, path: "edition-1"
      put :part_1
      get :edit_part_2, path: "edition-2"
      put :part_2
      get :submission_success, path: "outil-soumis"
    end
    resources :comments, controller: "tools/comments", only: [:create]
    resources :steps, controller: "tools/steps", only: [:destroy]
    resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
    resources :links, controller: "tools/links"
    resources :trainings, controller: "tools/trainings", only: [:show], path: "parcours-formations"
  end
  resources :tags, only: [:index]
  resources :basic_pages, only: [:show], path: "pages"
  resource :sitemap, only: [:show]
  put "/accept_cookies", to: "home#accept_cookies"
  get "/:filename", to: "statics#show"

  root to: 'axes#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/theme.rb
# frozen_string_literal: true

class Theme < ApplicationRecord
  # Configurations =============================================================
  include Sortable
  include Seoable

  acts_as_list

  # Associations ===============================================================

  has_many :axes, dependent: :restrict_with_exception
  has_many :tools, through: :axes
  has_one :basic_page, dependent: :destroy

  # Validations ================================================================
  validates :title, presence: true

  # Callbacks ==================================================================
  private def create_theme_pages
    about_page = BasicPage.where(theme_id: self.id, id_key: 'about').first_or_initialize
    about_page.title = "A propos"
    about_page.save

    cgu_page = BasicPage.where(theme_id: self.id, id_key: 'cgu').first_or_initialize
    cgu_page.title = "Conditions Générales d'Utilisation"
    cgu_page.save

  end
  after_create :create_theme_pages

  # Scopes =====================================================================
  scope :enabled, -> { where(enabled: true) }

  scope :by_title, ->(val) {
    val.downcase!
    where(arel_table[:title].matches("%#{val}%"))
  }

  # Class Methods ==============================================================
  def self.apply_filters(params)
    klass = self

    klass = klass.by_title(params[:by_title]) if params[:by_title].present?

    klass.apply_sorts(params)
  end

  def self.default
    where(id_key: 'mobility').first || first
  end

  # Instance Methods ===========================================================
end

app/controllers/admin/themes_controller.rb
# frozen_string_literal: true

class Admin::ThemesController < Admin::BaseController
  before_action :find_theme, only: %i(edit update position destroy)

  def index
    params[:sort] ||= 'sort_by_position asc'
    @themes = Theme.apply_filters(params).paginate(per_page: 20, page: params[:page])
  end

  def new
    @theme = Theme.new
    @theme.build_seo
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      flash[:notice] = 'La thématique a été créée avec succès'
      redirect_to params[:continue].present? ? edit_admin_theme_path(@theme) : admin_themes_path
    else
      flash[:error] = "Une erreur s'est produite lors de la création de la thématique"
      render :new
    end
  end

  def edit; end

  def update
    if @theme.update_attributes(theme_params)
      flash[:notice] = 'La thématique a été mise à jour avec succès'
      redirect_to params[:continue].present? ? edit_admin_theme_path(@theme) : admin_themes_path
    else
      flash[:error] = "Une erreur s'est produite lors de la mise à jour de la thématique"
      render :edit
    end
  end

  def position
    if params[:position].present?
      @theme.insert_at params[:position].to_i
      flash[:notice] = 'Les thématiques ont été réordonnées avec succès'
    end
    redirect_to admin_themes_path
  end

  def destroy
    begin
      flash[:notice] = 'La thématique a été supprimée avec succès' if @theme.destroy
    rescue ActiveRecord::DeleteRestrictionError
      flash[:error] = 'Cette thématique ne peut être supprimée car des éléments lui sont dépendants'
    end
    redirect_to admin_themes_path
  end

  private

  def find_theme
    @theme = Theme.from_param params[:id]
  end

  # strong parameters
  def theme_params
    params.require(:theme).permit(:title, :enabled, seo_attributes: %i(slug title keywords description id))
  end
end

app/helpers/theme_helper.rb
# frozen_string_literal: true

module ThemeHelper
  def theme_options(themes = Theme.all)
    themes.order(position: :asc).map do |theme|
      [theme.title, theme.id]
    end
  end
end

app/views/admin/themes/_form.html.slim
= f.hm_form_errors

.form-group.row
  .form-label-default
    | Affiché ?
  .controls-default
    .form-check.form-check-inline
      label.form-check-label
        => f.radio_button :enabled, true
        | Oui
      label.form-check-label
        => f.radio_button :enabled, false
        | Non

= f.hm_text_field :title, {}, {class: "required"}

= render partial: "admin/seos/fields_for_form", locals: {f: f}

.form-group.row
  .form-actions
    hr
    => f.submit button_name, class: "btn btn-primary", style: "margin-right: 2px", id: "submit_and_leave"
    => f.submit name: "continue", value: "#{button_name_2}", class: "btn btn-default", style: "margin-right: 2px", id: "submit_and_stay"
    = link_to "Annuler", admin_themes_path, class: "btn"

.form-group.row
  label.form-label-default
  .controls-default
    small: em.text-muted Les champs marqués d'une * sont obligatoires

app/views/admin/themes/_layout_form.html.slim
- content_for :current_navigation_section, :themes

.title-block
  h1
    | Gestion des thématiques
    = link_to admin_themes_path, class: 'btn btn-default float-right' do
      .glyphicon.glyphicon-arrow-left
      |  Retour

.card
  - if !@theme.new_record?

    h2.card-header
      | Edition de la thématique
      em=< @theme.title

    .card-block
      .row
        .col-md-2.border-right
          dl
            dt Date création :
            dd= l @theme.created_at.to_date
            dt Dernière mise à jour :
            dd= l @theme.updated_at
        .col-md-10
          = yield
          
  - else
    h2.card-header Créer une nouvelle thématique

    .card-block
      = yield

app/views/admin/themes/_layout_index.html.slim
- content_for :current_navigation_section, :themes

.title-block
  h1
    | Gestion des thématiques

    = link_to new_admin_theme_path, class: "btn btn-info float-right" do
     span.glyphicon.glyphicon-plus>
     | Ajouter une thématique

.card.card-block
  .content-main
    small.float-right = I18n.t("results", count: @themes.count)
    = yield

app/views/admin/themes/edit.html.slim
= render layout: 'layout_form' do
  = form_for @theme, as: :theme, url: admin_theme_path(@theme), html: {class: "form-horizontal"} do |f| 
    = render partial: "form", locals: {f: f, button_name: "Enregistrer les modifications", button_name_2: "Enregistrer et continuer l'édition"}

app/views/admin/themes/index.html.slim
= render layout: 'layout_index' do 

  table.table.table-striped.table-hover.table-sm
    thead.thead-inverse
      tr
        th= hm_sort 'sort_by_position', label: 'Position'
        th= hm_sort 'sort_by_title', label: 'Titre'
        th Nb axes
        th= hm_sort 'sort_by_enabled', label: 'Affiché?'
        th 
    tbody
      - max_position    = @themes.map( &:position ).compact.max || 1
      - position_select = (1..max_position).map {|i| [i,i] }
      - @themes.each do |theme| 
        tr
          td 
            = form_tag position_admin_theme_path(theme), method: :patch do
              = select_tag  :position, 
                            options_for_select( position_select, theme.position ),
                            onchange: '$(this).parent().submit();',
                            class: "form-control input-sm", style: "width:70px", id: nil 
          td= theme.title
          td= link_to admin_axes_path(by_theme: theme.id), class: "btn btn-default btn-sm" do
            i.fa.fa-list>
            => theme.axes.count
          td
            span class="badge badge-#{boolean_class(theme.enabled)}" = boolean_title(theme.enabled)
          td.action-btns
            => link_to raw("<span class='glyphicon glyphicon-pencil'></span>"), edit_admin_theme_path(theme),
              class: "btn btn-sm btn-info", title: "Editer"
            = link_to raw("<span class='glyphicon glyphicon-trash'></span>"), admin_theme_path(theme),
              method: :delete, data: {confirm: "Confirmer la suppression ?"}, title: "Supprimer", class: "btn btn-sm btn-danger"
      
      - if @themes.empty?
        tr
          td colspan="7"
            p.text-center: em.text-muted Aucun résultat


  = will_paginate @themes, renderer: WillPaginateBoostrap4Renderer

app/views/admin/themes/new.html.slim
= render layout: 'layout_form' do 
  = form_for @theme, as: :theme, url: admin_themes_path, html: {class: "form-horizontal"} do |f| 
    = render partial: "form", locals: {f: f, button_name: "Créer", button_name_2: "Créer et continuer l'édition"}