config/routes.rb
Rails.application.routes.draw do

  devise_for :admin

  # Concerns ======================================

  concern :positionable do
    patch :position, on: :member
  end

  # Admin ======================================

  namespace :admin do
    resources :admins
    resources :basic_pages, concerns: :positionable
    resources :themes, concerns: :positionable
    resources :axes, concerns: :positionable
    resources :tags, concerns: :positionable
    resources :tool_categories, concerns: :positionable
    resources :trainings
    resources :training_tools, only: [:destroy], concerns: :positionable
    resources :comments, only: [:index, :destroy] do
      member do
        patch :accept 
        patch :reject
      end
    end
    resources :tools do
      member do
        patch :accept 
        patch :reject
        get :edit_part_1
        put :part_1
        get :edit_part_2
        put :part_2
      end
      resources :steps, controller: "tools/steps", only: [:destroy]
      resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
      resources :links, controller: "tools/links"
    end
    resources :seos, only: [:index, :edit, :update]
    root to: 'dashboard#index'
  end

  # Front ======================================
  
  resources :axes, only: [:index]
  resources :tools, only: [:index, :show, :new, :create, :update], 
    path: 'outils', path_names: {new: "nouveau"} do
    member do
      get :edit_part_1, path: "edition-1"
      put :part_1
      get :edit_part_2, path: "edition-2"
      put :part_2
      get :submission_success, path: "outil-soumis"
    end
    resources :comments, controller: "tools/comments", only: [:create]
    resources :steps, controller: "tools/steps", only: [:destroy]
    resources :tool_attachments, as: :attachments, controller: "tools/tool_attachments"
    resources :links, controller: "tools/links"
    resources :trainings, controller: "tools/trainings", only: [:show], path: "parcours-formations"
  end
  resources :tags, only: [:index]
  resources :basic_pages, only: [:show], path: "pages"
  resource :sitemap, only: [:show]
  put "/accept_cookies", to: "home#accept_cookies"
  get "/:filename", to: "statics#show"

  root to: 'axes#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
# frozen_string_literal: true

class Training < ApplicationRecord
  # Configurations =============================================================
  include Sortable
  include Seoable

  acts_as_list

  # Associations ===============================================================

  has_many :training_tools, -> { order 'training_tools.position' }, dependent: :destroy
  has_many :tools, through: :training_tools

  # Callbacks ==================================================================
  validates :title, presence: true

  # Scopes =====================================================================
  scope :enabled, -> { where(enabled: true) }

  scope :by_title, ->(val) {
    val.downcase!
    where(arel_table[:title].matches("%#{val}%"))
  }

  # Class Methods ==============================================================
  def self.apply_filters(params)
    klass = self

    klass = klass.by_title(params[:by_title]) if params[:by_title].present?

    klass.apply_sorts(params)
  end

  # Instance Methods ===========================================================

  # private #=====================================================================
end

app/controllers/admin/trainings_controller.rb
# frozen_string_literal: true

class Admin::TrainingsController < Admin::BaseController
  before_action :find_training, only: %i(edit update position destroy)

  def index
    params[:sort] ||= 'sort_by_position asc'
    @trainings = Training.apply_filters(params).paginate(per_page: 20, page: params[:page])
  end

  def new
    @training = Training.new
    @training.build_seo
  end

  def create
    @training = Training.new(training_params)
    if @training.save
      flash[:notice] = 'Le parcours a été créé avec succès'
      redirect_to params[:continue].present? ? edit_admin_training_path(@training) : admin_trainings_path
    else
      flash[:error] = "Une erreur s'est produite lors de la création du parcours"
      render :new
    end
  end

  def edit; end

  def update
    if @training.update_attributes(training_params)
      flash[:notice] = 'Le parcours a été mis à jour avec succès'
      redirect_to params[:continue].present? ? edit_admin_training_path(@training) : admin_trainings_path
    else
      flash[:error] = "Une erreur s'est produite lors de la mise à jour du parcours"
      render :edit
    end
  end

  def position
    if params[:position].present?
      @training.insert_at params[:position].to_i
      flash[:notice] = 'Les parcours ont été réordonnés avec succès'
    end
    redirect_to admin_trainings_path
  end

  def destroy
    @training.destroy
    flash[:notice] = 'Le parcours a été supprimé avec succès'
    redirect_to admin_trainings_path
  end

  private

  def find_training
    @training = Training.from_param params[:id]
  end

  # strong parameters
  def training_params
    params.require(:training).permit(:title, :enabled, :tool_ids, tool_ids: [], seo_attributes: %i(slug title keywords description id))
  end
end

app/controllers/tools/trainings_controller.rb
# frozen_string_literal: true

class Tools::TrainingsController < Tools::BaseController
  
  def show
    @training = @tool.trainings.from_param params[:id]
    @tools = @training.tools.enabled
                          .apply_filters(params)
                          .includes(:axis)
                          .includes(:seo)
                          .includes(:tool_category)
                          .includes(:tool_tags)
                          .includes(:tags)
                          .paginate(per_page: 20, page: params[:page])
  end

  private

end

app/views/admin/trainings/_form.html.slim
= f.hm_form_errors

.form-group.row
  .form-label-default
    | Affiché ?
  .controls-default
    .form-check.form-check-inline
      label.form-check-label
        => f.radio_button :enabled, true
        | Oui
      label.form-check-label
        => f.radio_button :enabled, false
        | Non


= f.hm_text_field :title, {}, {class: "required"}

- if f.object.new_record?
  .form-group.row
    .form-label-default
    .controls-xlarge
      p.form-text.text-muted.small: em Renseignez le titre du parcours et créez-le pour pouvoir y ajouter des outils.

-else

  .form-group.row data-is-tt-container='tool' data-is-tt-path="#{admin_tools_path}"
    .form-label-default
      label Ajouter un outil
    .controls-xlarge
      => text_field_tag 'tool_title', params[:tool_title], \
            class: "form-control", placeholder: "Recherchez par titre", data: {is_tt_input: 'tool'}, autocomplete: 'off' 

  table.table.table-hover.table-sm
      thead
        tr
          th= hm_sort 'sort_by_title', label: 'Outil'
          th= hm_sort 'sort_by_axis_id', label: 'Axe'
          th= hm_sort 'sort_by_tool_category_id', label: 'Catégorie'
          th= hm_sort 'sort_by_state', label: 'Etat'
          th= hm_sort 'sort_by_position', label: 'Position'
          th Actions
      tbody data-is-tool-list=true
        - max_position    = f.object.training_tools.map( &:position ).compact.max || 1
        - position_select = (1..max_position).map {|i| [i,i] }
        - f.object.training_tools.order(position: :asc).each do |training_tool| 
          - tool = training_tool.tool
          tr
            = f.hidden_field :tool_ids, multiple: true, value: [training_tool.tool_id]
            td= link_to tool.title, edit_part_1_admin_tool_path(tool)
            td= tool.axis.title
            td= tool.tool_category.title
            td
              span class="badge badge-#{tool_state_style(tool.state)}"= tool_state_title(tool.state)
            td 
              = form_tag position_admin_training_tool_path(training_tool), method: :patch, data: {is_position_form: training_tool.id} do
                = select_tag  :position, 
                              options_for_select( position_select, training_tool.position ),
                              onchange: '$(this).parent("[data-is-position-form]").submit();',
                              class: "form-control input-sm", style: "width:70px", id: nil 
            td.action-btns.border-left
              = link_to raw("<span class='glyphicon glyphicon-trash'></span>"), admin_training_tool_path(training_tool),
                method: :delete, data: {confirm: "Confirmer la suppression ?"}, title: "Supprimer", class: "btn btn-sm btn-danger"

  = render partial: "admin/seos/fields_for_form", locals: {f: f}

.form-group.row
  .form-actions
    hr
    => f.submit button_name, class: "btn btn-primary", style: "margin-right: 2px", id: "submit_and_leave"
    => f.submit name: "continue", value: "#{button_name_2}", class: "btn btn-default", style: "margin-right: 2px", id: "submit_and_stay"
    = link_to "Annuler", admin_trainings_path, class: "btn"

.form-group.row
  label.form-label-default
  .controls-default
    small: em.text-muted Les champs marqués d'une * sont obligatoires

= render "admin/trainings/hb_training_tool"


coffee:
  new TrainingForm()

app/views/admin/trainings/_hb_training_tool.html.slim
= handlebars_template(:TrainingTool) do
  tr.table-warning data-is-tool="{{id}}"
    = hidden_field_tag "training[tool_ids][]", "{{id}}" ,multiple: true
    td= "{{title}}"
    td= "{{axis_title}}"
    td= "{{tool_category_title}}"
    td colspan=2
      em Enregistrer les modifications du parcours pour valider l'outil et pouvoir changer sa position 
    td.action-btns.border-left
      = link_to raw("<span class='glyphicon glyphicon-trash'></span>"), "javascript:void(0)",
        method: :delete, data: {trigger_deletion: "{{id}}"}, title: "Supprimer", class: "btn btn-sm btn-danger"

app/views/admin/trainings/_layout_form.html.slim
- content_for :current_navigation_section, :trainings

.title-block
  h1
    | Gestion des parcours de formation
    = link_to admin_trainings_path, class: 'btn btn-default float-right' do
      .glyphicon.glyphicon-arrow-left
      |  Retour

.card
  - if !@training.new_record?

    h2.card-header
      | Edition du parcours
      em=< @training.title

    .card-block
      .row
        .col-md-10
          = yield
        .col-md-2.border-right
          dl
            dt Date création :
            dd= l @training.created_at.to_date
            dt Dernière mise à jour :
            dd= l @training.updated_at
          
  - else
    h2.card-header Créer un nouveau parcours

    .card-block
      = yield

app/views/admin/trainings/_layout_index.html.slim
- content_for :current_navigation_section, :trainings

.title-block
  h1
    | Gestion des parcours de formation

    = link_to new_admin_training_path, class: "btn btn-info float-right" do
     span.glyphicon.glyphicon-plus>
     | Ajouter un parcours

.card.card-block.card-search
  = form_tag admin_trainings_path, method: :get, data: {is_filter_form: true} do

    .lead
      | Filtrer votre recherche
    .row
      .form-group.col-3
        label.sr-only Par titre
        => text_field_tag 'by_title', params[:by_title], \
          class: "form-control", placeholder: "par titre"

      / .form-group.col-3
      /   = select_tag :by_theme, \
      /         options_for_select(theme_options, params[:by_theme]), \
      /         prompt: "Tous les thèmes",\
      /         class: "form-control", \
      /         onchange: "$('[data-is-filter-form]').submit()"

      .form-group.col-5
        = submit_tag "Appliquer", class: "btn btn-success"
        = link_to admin_trainings_path, class: "btn btn-sm" do
          span.glyphicon.glyphicon-repeat>
          | Réinitialiser

.card.card-block
  .content-main
    small.float-right = I18n.t("results", count: @trainings.count)
    = yield

app/views/admin/trainings/edit.html.slim
= render layout: 'layout_form' do
  = form_for @training, as: :training, url: admin_training_path(@training), html: {class: "form-horizontal"} do |f| 
    = render partial: "form", locals: {f: f, button_name: "Enregistrer les modifications", button_name_2: "Enregistrer et continuer l'édition"}

app/views/admin/trainings/index.html.slim
= render layout: 'layout_index' do 

  table.table.table-striped.table-hover.table-sm
    thead.thead-inverse
      tr
        / th= hm_sort 'sort_by_position', label: 'Position'
        th= hm_sort 'sort_by_title', label: 'Titre'
        th Nb outils
        th= hm_sort 'sort_by_enabled', label: 'Affiché?'
        th 
    tbody
      / - max_position    = @trainings.map( &:position ).compact.max || 1
      / - position_select = (1..max_position).map {|i| [i,i] }
      - @trainings.each do |training| 
        tr
          / td 
          /   = form_tag position_admin_training_path(training), method: :patch do
          /     = select_tag  :position, 
          /                   options_for_select( position_select, training.position ),
          /                   onchange: '$(this).parent().submit();',
          /                   class: "form-control input-sm", style: "width:70px", id: nil 
          td= link_to training.title, edit_admin_training_path(training)
          td
            i.fa.fa-list>
            => training.tools.count
          td
            span class="badge badge-#{boolean_class(training.enabled)}" = boolean_title(training.enabled)
          td.action-btns
            => link_to raw("<span class='glyphicon glyphicon-pencil'></span>"), edit_admin_training_path(training),
              class: "btn btn-sm btn-info", title: "Editer"
            = link_to raw("<span class='glyphicon glyphicon-trash'></span>"), admin_training_path(training),
              method: :delete, data: {confirm: "Confirmer la suppression ?"}, title: "Supprimer", class: "btn btn-sm btn-danger"
      
      - if @trainings.empty?
        tr
          td colspan="7"
            p.text-center: em.text-muted Aucun résultat


  = will_paginate @trainings, renderer: WillPaginateBoostrap4Renderer

app/views/admin/trainings/new.html.slim
= render layout: 'layout_form' do 
  = form_for @training, as: :training, url: admin_trainings_path, html: {class: "form-horizontal"} do |f| 
    = render partial: "form", locals: {f: f, button_name: "Créer", button_name_2: "Créer et continuer l'édition"}